<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.4" tiledversion="1.4.3" name="Example" tilewidth="232" tileheight="110" tilecount="3" columns="0">
 <tileoffset x="-12" y="6"/>
 <grid orientation="orthogonal" width="1" height="1"/>
<tile id='0'><image width='256' height='352' source='../Tiles/balcony_stone_N.png'/></tile>
<tile id='1'><image width='256' height='352' source='../Tiles/balcony_stone_E.png'/></tile>
<tile id='2'><image width='256' height='352' source='../Tiles/balcony_stone_S.png'/></tile>
<tile id='3'><image width='256' height='352' source='../Tiles/balcony_stone_W.png'/></tile>
<tile id='4'><image width='256' height='352' source='../Tiles/balcony_wood_N.png'/></tile>
<tile id='5'><image width='256' height='352' source='../Tiles/balcony_wood_E.png'/></tile>
<tile id='6'><image width='256' height='352' source='../Tiles/balcony_wood_S.png'/></tile>
<tile id='7'><image width='256' height='352' source='../Tiles/balcony_wood_W.png'/></tile>
<tile id='8'><image width='256' height='352' source='../Tiles/building_stack_N.png'/></tile>
<tile id='9'><image width='256' height='352' source='../Tiles/building_stack_E.png'/></tile>
<tile id='10'><image width='256' height='352' source='../Tiles/building_stack_S.png'/></tile>
<tile id='11'><image width='256' height='352' source='../Tiles/building_stack_W.png'/></tile>
<tile id='12'><image width='256' height='352' source='../Tiles/building_stackBeige_N.png'/></tile>
<tile id='13'><image width='256' height='352' source='../Tiles/building_stackBeige_E.png'/></tile>
<tile id='14'><image width='256' height='352' source='../Tiles/building_stackBeige_S.png'/></tile>
<tile id='15'><image width='256' height='352' source='../Tiles/building_stackBeige_W.png'/></tile>
<tile id='16'><image width='256' height='352' source='../Tiles/building_stackCorner_N.png'/></tile>
<tile id='17'><image width='256' height='352' source='../Tiles/building_stackCorner_E.png'/></tile>
<tile id='18'><image width='256' height='352' source='../Tiles/building_stackCorner_S.png'/></tile>
<tile id='19'><image width='256' height='352' source='../Tiles/building_stackCorner_W.png'/></tile>
<tile id='20'><image width='256' height='352' source='../Tiles/building_stackCornerBeige_N.png'/></tile>
<tile id='21'><image width='256' height='352' source='../Tiles/building_stackCornerBeige_E.png'/></tile>
<tile id='22'><image width='256' height='352' source='../Tiles/building_stackCornerBeige_S.png'/></tile>
<tile id='23'><image width='256' height='352' source='../Tiles/building_stackCornerBeige_W.png'/></tile>
<tile id='24'><image width='256' height='352' source='../Tiles/castle_end_N.png'/></tile>
<tile id='25'><image width='256' height='352' source='../Tiles/castle_end_E.png'/></tile>
<tile id='26'><image width='256' height='352' source='../Tiles/castle_end_S.png'/></tile>
<tile id='27'><image width='256' height='352' source='../Tiles/castle_end_W.png'/></tile>
<tile id='28'><image width='256' height='352' source='../Tiles/castle_endRound_N.png'/></tile>
<tile id='29'><image width='256' height='352' source='../Tiles/castle_endRound_E.png'/></tile>
<tile id='30'><image width='256' height='352' source='../Tiles/castle_endRound_S.png'/></tile>
<tile id='31'><image width='256' height='352' source='../Tiles/castle_endRound_W.png'/></tile>
<tile id='32'><image width='256' height='352' source='../Tiles/castle_endRuined_N.png'/></tile>
<tile id='33'><image width='256' height='352' source='../Tiles/castle_endRuined_E.png'/></tile>
<tile id='34'><image width='256' height='352' source='../Tiles/castle_endRuined_S.png'/></tile>
<tile id='35'><image width='256' height='352' source='../Tiles/castle_endRuined_W.png'/></tile>
<tile id='36'><image width='256' height='352' source='../Tiles/castle_towerBeigeBase_N.png'/></tile>
<tile id='37'><image width='256' height='352' source='../Tiles/castle_towerBeigeBase_E.png'/></tile>
<tile id='38'><image width='256' height='352' source='../Tiles/castle_towerBeigeBase_S.png'/></tile>
<tile id='39'><image width='256' height='352' source='../Tiles/castle_towerBeigeBase_W.png'/></tile>
<tile id='40'><image width='256' height='352' source='../Tiles/castle_towerBeigeTop_N.png'/></tile>
<tile id='41'><image width='256' height='352' source='../Tiles/castle_towerBeigeTop_E.png'/></tile>
<tile id='42'><image width='256' height='352' source='../Tiles/castle_towerBeigeTop_S.png'/></tile>
<tile id='43'><image width='256' height='352' source='../Tiles/castle_towerBeigeTop_W.png'/></tile>
<tile id='44'><image width='256' height='352' source='../Tiles/castle_towerBrownBase_N.png'/></tile>
<tile id='45'><image width='256' height='352' source='../Tiles/castle_towerBrownBase_E.png'/></tile>
<tile id='46'><image width='256' height='352' source='../Tiles/castle_towerBrownBase_S.png'/></tile>
<tile id='47'><image width='256' height='352' source='../Tiles/castle_towerBrownBase_W.png'/></tile>
<tile id='48'><image width='256' height='352' source='../Tiles/castle_towerBrownTop_N.png'/></tile>
<tile id='49'><image width='256' height='352' source='../Tiles/castle_towerBrownTop_E.png'/></tile>
<tile id='50'><image width='256' height='352' source='../Tiles/castle_towerBrownTop_S.png'/></tile>
<tile id='51'><image width='256' height='352' source='../Tiles/castle_towerBrownTop_W.png'/></tile>
<tile id='52'><image width='256' height='352' source='../Tiles/castle_towerCenter_N.png'/></tile>
<tile id='53'><image width='256' height='352' source='../Tiles/castle_towerCenter_E.png'/></tile>
<tile id='54'><image width='256' height='352' source='../Tiles/castle_towerCenter_S.png'/></tile>
<tile id='55'><image width='256' height='352' source='../Tiles/castle_towerCenter_W.png'/></tile>
<tile id='56'><image width='256' height='352' source='../Tiles/castle_towerGreenBase_N.png'/></tile>
<tile id='57'><image width='256' height='352' source='../Tiles/castle_towerGreenBase_E.png'/></tile>
<tile id='58'><image width='256' height='352' source='../Tiles/castle_towerGreenBase_S.png'/></tile>
<tile id='59'><image width='256' height='352' source='../Tiles/castle_towerGreenBase_W.png'/></tile>
<tile id='60'><image width='256' height='352' source='../Tiles/castle_towerGreenTop_N.png'/></tile>
<tile id='61'><image width='256' height='352' source='../Tiles/castle_towerGreenTop_E.png'/></tile>
<tile id='62'><image width='256' height='352' source='../Tiles/castle_towerGreenTop_S.png'/></tile>
<tile id='63'><image width='256' height='352' source='../Tiles/castle_towerGreenTop_W.png'/></tile>
<tile id='64'><image width='256' height='352' source='../Tiles/castle_towerPurpleBase_N.png'/></tile>
<tile id='65'><image width='256' height='352' source='../Tiles/castle_towerPurpleBase_E.png'/></tile>
<tile id='66'><image width='256' height='352' source='../Tiles/castle_towerPurpleBase_S.png'/></tile>
<tile id='67'><image width='256' height='352' source='../Tiles/castle_towerPurpleBase_W.png'/></tile>
<tile id='68'><image width='256' height='352' source='../Tiles/castle_towerPurpleTop_N.png'/></tile>
<tile id='69'><image width='256' height='352' source='../Tiles/castle_towerPurpleTop_E.png'/></tile>
<tile id='70'><image width='256' height='352' source='../Tiles/castle_towerPurpleTop_S.png'/></tile>
<tile id='71'><image width='256' height='352' source='../Tiles/castle_towerPurpleTop_W.png'/></tile>
<tile id='72'><image width='256' height='352' source='../Tiles/cliff_N.png'/></tile>
<tile id='73'><image width='256' height='352' source='../Tiles/cliff_E.png'/></tile>
<tile id='74'><image width='256' height='352' source='../Tiles/cliff_S.png'/></tile>
<tile id='75'><image width='256' height='352' source='../Tiles/cliff_W.png'/></tile>
<tile id='76'><image width='256' height='352' source='../Tiles/cliff_corner_N.png'/></tile>
<tile id='77'><image width='256' height='352' source='../Tiles/cliff_corner_E.png'/></tile>
<tile id='78'><image width='256' height='352' source='../Tiles/cliff_corner_S.png'/></tile>
<tile id='79'><image width='256' height='352' source='../Tiles/cliff_corner_W.png'/></tile>
<tile id='80'><image width='256' height='352' source='../Tiles/cliff_cornerInner_N.png'/></tile>
<tile id='81'><image width='256' height='352' source='../Tiles/cliff_cornerInner_E.png'/></tile>
<tile id='82'><image width='256' height='352' source='../Tiles/cliff_cornerInner_S.png'/></tile>
<tile id='83'><image width='256' height='352' source='../Tiles/cliff_cornerInner_W.png'/></tile>
<tile id='84'><image width='256' height='352' source='../Tiles/cliff_entrance_N.png'/></tile>
<tile id='85'><image width='256' height='352' source='../Tiles/cliff_entrance_E.png'/></tile>
<tile id='86'><image width='256' height='352' source='../Tiles/cliff_entrance_S.png'/></tile>
<tile id='87'><image width='256' height='352' source='../Tiles/cliff_entrance_W.png'/></tile>
<tile id='88'><image width='256' height='352' source='../Tiles/cliff_top_N.png'/></tile>
<tile id='89'><image width='256' height='352' source='../Tiles/cliff_top_E.png'/></tile>
<tile id='90'><image width='256' height='352' source='../Tiles/cliff_top_S.png'/></tile>
<tile id='91'><image width='256' height='352' source='../Tiles/cliff_top_W.png'/></tile>
<tile id='92'><image width='256' height='352' source='../Tiles/cliff_topCorner_N.png'/></tile>
<tile id='93'><image width='256' height='352' source='../Tiles/cliff_topCorner_E.png'/></tile>
<tile id='94'><image width='256' height='352' source='../Tiles/cliff_topCorner_S.png'/></tile>
<tile id='95'><image width='256' height='352' source='../Tiles/cliff_topCorner_W.png'/></tile>
<tile id='96'><image width='256' height='352' source='../Tiles/cliff_topCornerInner_N.png'/></tile>
<tile id='97'><image width='256' height='352' source='../Tiles/cliff_topCornerInner_E.png'/></tile>
<tile id='98'><image width='256' height='352' source='../Tiles/cliff_topCornerInner_S.png'/></tile>
<tile id='99'><image width='256' height='352' source='../Tiles/cliff_topCornerInner_W.png'/></tile>
<tile id='100'><image width='256' height='352' source='../Tiles/cliff_topEntrance_N.png'/></tile>
<tile id='101'><image width='256' height='352' source='../Tiles/cliff_topEntrance_E.png'/></tile>
<tile id='102'><image width='256' height='352' source='../Tiles/cliff_topEntrance_S.png'/></tile>
<tile id='103'><image width='256' height='352' source='../Tiles/cliff_topEntrance_W.png'/></tile>
<tile id='104'><image width='256' height='352' source='../Tiles/dirt_corner_N.png'/></tile>
<tile id='105'><image width='256' height='352' source='../Tiles/dirt_corner_E.png'/></tile>
<tile id='106'><image width='256' height='352' source='../Tiles/dirt_corner_S.png'/></tile>
<tile id='107'><image width='256' height='352' source='../Tiles/dirt_corner_W.png'/></tile>
<tile id='108'><image width='256' height='352' source='../Tiles/fence_wood_N.png'/></tile>
<tile id='109'><image width='256' height='352' source='../Tiles/fence_wood_E.png'/></tile>
<tile id='110'><image width='256' height='352' source='../Tiles/fence_wood_S.png'/></tile>
<tile id='111'><image width='256' height='352' source='../Tiles/fence_wood_W.png'/></tile>
<tile id='112'><image width='256' height='352' source='../Tiles/fence_woodCorner_N.png'/></tile>
<tile id='113'><image width='256' height='352' source='../Tiles/fence_woodCorner_E.png'/></tile>
<tile id='114'><image width='256' height='352' source='../Tiles/fence_woodCorner_S.png'/></tile>
<tile id='115'><image width='256' height='352' source='../Tiles/fence_woodCorner_W.png'/></tile>
<tile id='116'><image width='256' height='352' source='../Tiles/fence_woodCurve_N.png'/></tile>
<tile id='117'><image width='256' height='352' source='../Tiles/fence_woodCurve_E.png'/></tile>
<tile id='118'><image width='256' height='352' source='../Tiles/fence_woodCurve_S.png'/></tile>
<tile id='119'><image width='256' height='352' source='../Tiles/fence_woodCurve_W.png'/></tile>
<tile id='120'><image width='256' height='352' source='../Tiles/fence_woodDouble_N.png'/></tile>
<tile id='121'><image width='256' height='352' source='../Tiles/fence_woodDouble_E.png'/></tile>
<tile id='122'><image width='256' height='352' source='../Tiles/fence_woodDouble_S.png'/></tile>
<tile id='123'><image width='256' height='352' source='../Tiles/fence_woodDouble_W.png'/></tile>
<tile id='124'><image width='256' height='352' source='../Tiles/fence_woodDoubleCorner_N.png'/></tile>
<tile id='125'><image width='256' height='352' source='../Tiles/fence_woodDoubleCorner_E.png'/></tile>
<tile id='126'><image width='256' height='352' source='../Tiles/fence_woodDoubleCorner_S.png'/></tile>
<tile id='127'><image width='256' height='352' source='../Tiles/fence_woodDoubleCorner_W.png'/></tile>
<tile id='128'><image width='256' height='352' source='../Tiles/fence_woodDoubleCurve_N.png'/></tile>
<tile id='129'><image width='256' height='352' source='../Tiles/fence_woodDoubleCurve_E.png'/></tile>
<tile id='130'><image width='256' height='352' source='../Tiles/fence_woodDoubleCurve_S.png'/></tile>
<tile id='131'><image width='256' height='352' source='../Tiles/fence_woodDoubleCurve_W.png'/></tile>
<tile id='132'><image width='256' height='352' source='../Tiles/fence_woodDoubleEnd_N.png'/></tile>
<tile id='133'><image width='256' height='352' source='../Tiles/fence_woodDoubleEnd_E.png'/></tile>
<tile id='134'><image width='256' height='352' source='../Tiles/fence_woodDoubleEnd_S.png'/></tile>
<tile id='135'><image width='256' height='352' source='../Tiles/fence_woodDoubleEnd_W.png'/></tile>
<tile id='136'><image width='256' height='352' source='../Tiles/fence_woodEnd_N.png'/></tile>
<tile id='137'><image width='256' height='352' source='../Tiles/fence_woodEnd_E.png'/></tile>
<tile id='138'><image width='256' height='352' source='../Tiles/fence_woodEnd_S.png'/></tile>
<tile id='139'><image width='256' height='352' source='../Tiles/fence_woodEnd_W.png'/></tile>
<tile id='140'><image width='256' height='352' source='../Tiles/furrow_N.png'/></tile>
<tile id='141'><image width='256' height='352' source='../Tiles/furrow_E.png'/></tile>
<tile id='142'><image width='256' height='352' source='../Tiles/furrow_S.png'/></tile>
<tile id='143'><image width='256' height='352' source='../Tiles/furrow_W.png'/></tile>
<tile id='144'><image width='256' height='352' source='../Tiles/furrow_crop_N.png'/></tile>
<tile id='145'><image width='256' height='352' source='../Tiles/furrow_crop_E.png'/></tile>
<tile id='146'><image width='256' height='352' source='../Tiles/furrow_crop_S.png'/></tile>
<tile id='147'><image width='256' height='352' source='../Tiles/furrow_crop_W.png'/></tile>
<tile id='148'><image width='256' height='352' source='../Tiles/furrow_cropWheat_N.png'/></tile>
<tile id='149'><image width='256' height='352' source='../Tiles/furrow_cropWheat_E.png'/></tile>
<tile id='150'><image width='256' height='352' source='../Tiles/furrow_cropWheat_S.png'/></tile>
<tile id='151'><image width='256' height='352' source='../Tiles/furrow_cropWheat_W.png'/></tile>
<tile id='152'><image width='256' height='352' source='../Tiles/furrow_end_N.png'/></tile>
<tile id='153'><image width='256' height='352' source='../Tiles/furrow_end_E.png'/></tile>
<tile id='154'><image width='256' height='352' source='../Tiles/furrow_end_S.png'/></tile>
<tile id='155'><image width='256' height='352' source='../Tiles/furrow_end_W.png'/></tile>
<tile id='156'><image width='256' height='352' source='../Tiles/grass_block_N.png'/></tile>
<tile id='157'><image width='256' height='352' source='../Tiles/grass_block_E.png'/></tile>
<tile id='158'><image width='256' height='352' source='../Tiles/grass_block_S.png'/></tile>
<tile id='159'><image width='256' height='352' source='../Tiles/grass_block_W.png'/></tile>
<tile id='160'><image width='256' height='352' source='../Tiles/roof_gableCornerBeige_N.png'/></tile>
<tile id='161'><image width='256' height='352' source='../Tiles/roof_gableCornerBeige_E.png'/></tile>
<tile id='162'><image width='256' height='352' source='../Tiles/roof_gableCornerBeige_S.png'/></tile>
<tile id='163'><image width='256' height='352' source='../Tiles/roof_gableCornerBeige_W.png'/></tile>
<tile id='164'><image width='256' height='352' source='../Tiles/roof_gableCornerBrown_N.png'/></tile>
<tile id='165'><image width='256' height='352' source='../Tiles/roof_gableCornerBrown_E.png'/></tile>
<tile id='166'><image width='256' height='352' source='../Tiles/roof_gableCornerBrown_S.png'/></tile>
<tile id='167'><image width='256' height='352' source='../Tiles/roof_gableCornerBrown_W.png'/></tile>
<tile id='168'><image width='256' height='352' source='../Tiles/roof_gableCornerGreen_N.png'/></tile>
<tile id='169'><image width='256' height='352' source='../Tiles/roof_gableCornerGreen_E.png'/></tile>
<tile id='170'><image width='256' height='352' source='../Tiles/roof_gableCornerGreen_S.png'/></tile>
<tile id='171'><image width='256' height='352' source='../Tiles/roof_gableCornerGreen_W.png'/></tile>
<tile id='172'><image width='256' height='352' source='../Tiles/roof_gableCornerPurple_N.png'/></tile>
<tile id='173'><image width='256' height='352' source='../Tiles/roof_gableCornerPurple_E.png'/></tile>
<tile id='174'><image width='256' height='352' source='../Tiles/roof_gableCornerPurple_S.png'/></tile>
<tile id='175'><image width='256' height='352' source='../Tiles/roof_gableCornerPurple_W.png'/></tile>
<tile id='176'><image width='256' height='352' source='../Tiles/roof_roundCornerBeige_N.png'/></tile>
<tile id='177'><image width='256' height='352' source='../Tiles/roof_roundCornerBeige_E.png'/></tile>
<tile id='178'><image width='256' height='352' source='../Tiles/roof_roundCornerBeige_S.png'/></tile>
<tile id='179'><image width='256' height='352' source='../Tiles/roof_roundCornerBeige_W.png'/></tile>
<tile id='180'><image width='256' height='352' source='../Tiles/roof_roundCornerBrown_N.png'/></tile>
<tile id='181'><image width='256' height='352' source='../Tiles/roof_roundCornerBrown_E.png'/></tile>
<tile id='182'><image width='256' height='352' source='../Tiles/roof_roundCornerBrown_S.png'/></tile>
<tile id='183'><image width='256' height='352' source='../Tiles/roof_roundCornerBrown_W.png'/></tile>
<tile id='184'><image width='256' height='352' source='../Tiles/roof_roundCornerGreen_N.png'/></tile>
<tile id='185'><image width='256' height='352' source='../Tiles/roof_roundCornerGreen_E.png'/></tile>
<tile id='186'><image width='256' height='352' source='../Tiles/roof_roundCornerGreen_S.png'/></tile>
<tile id='187'><image width='256' height='352' source='../Tiles/roof_roundCornerGreen_W.png'/></tile>
<tile id='188'><image width='256' height='352' source='../Tiles/roof_roundCornerPurple_N.png'/></tile>
<tile id='189'><image width='256' height='352' source='../Tiles/roof_roundCornerPurple_E.png'/></tile>
<tile id='190'><image width='256' height='352' source='../Tiles/roof_roundCornerPurple_S.png'/></tile>
<tile id='191'><image width='256' height='352' source='../Tiles/roof_roundCornerPurple_W.png'/></tile>
<tile id='192'><image width='256' height='352' source='../Tiles/roof_slantCornerBeige_N.png'/></tile>
<tile id='193'><image width='256' height='352' source='../Tiles/roof_slantCornerBeige_E.png'/></tile>
<tile id='194'><image width='256' height='352' source='../Tiles/roof_slantCornerBeige_S.png'/></tile>
<tile id='195'><image width='256' height='352' source='../Tiles/roof_slantCornerBeige_W.png'/></tile>
<tile id='196'><image width='256' height='352' source='../Tiles/roof_slantCornerBrown_N.png'/></tile>
<tile id='197'><image width='256' height='352' source='../Tiles/roof_slantCornerBrown_E.png'/></tile>
<tile id='198'><image width='256' height='352' source='../Tiles/roof_slantCornerBrown_S.png'/></tile>
<tile id='199'><image width='256' height='352' source='../Tiles/roof_slantCornerBrown_W.png'/></tile>
<tile id='200'><image width='256' height='352' source='../Tiles/roof_slantCornerGreen_N.png'/></tile>
<tile id='201'><image width='256' height='352' source='../Tiles/roof_slantCornerGreen_E.png'/></tile>
<tile id='202'><image width='256' height='352' source='../Tiles/roof_slantCornerGreen_S.png'/></tile>
<tile id='203'><image width='256' height='352' source='../Tiles/roof_slantCornerGreen_W.png'/></tile>
<tile id='204'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerBeige_N.png'/></tile>
<tile id='205'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerBeige_E.png'/></tile>
<tile id='206'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerBeige_S.png'/></tile>
<tile id='207'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerBeige_W.png'/></tile>
<tile id='208'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerBrown_N.png'/></tile>
<tile id='209'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerBrown_E.png'/></tile>
<tile id='210'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerBrown_S.png'/></tile>
<tile id='211'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerBrown_W.png'/></tile>
<tile id='212'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerGreen_N.png'/></tile>
<tile id='213'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerGreen_E.png'/></tile>
<tile id='214'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerGreen_S.png'/></tile>
<tile id='215'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerGreen_W.png'/></tile>
<tile id='216'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerPurple_N.png'/></tile>
<tile id='217'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerPurple_E.png'/></tile>
<tile id='218'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerPurple_S.png'/></tile>
<tile id='219'><image width='256' height='352' source='../Tiles/roof_slantCornerInnerPurple_W.png'/></tile>
<tile id='220'><image width='256' height='352' source='../Tiles/roof_slantCornerPurple_N.png'/></tile>
<tile id='221'><image width='256' height='352' source='../Tiles/roof_slantCornerPurple_E.png'/></tile>
<tile id='222'><image width='256' height='352' source='../Tiles/roof_slantCornerPurple_S.png'/></tile>
<tile id='223'><image width='256' height='352' source='../Tiles/roof_slantCornerPurple_W.png'/></tile>
<tile id='224'><image width='256' height='352' source='../Tiles/tree_pine_N.png'/></tile>
<tile id='225'><image width='256' height='352' source='../Tiles/tree_pine_E.png'/></tile>
<tile id='226'><image width='256' height='352' source='../Tiles/tree_pine_S.png'/></tile>
<tile id='227'><image width='256' height='352' source='../Tiles/tree_pine_W.png'/></tile>
<tile id='228'><image width='256' height='352' source='../Tiles/tree_pineLarge_N.png'/></tile>
<tile id='229'><image width='256' height='352' source='../Tiles/tree_pineLarge_E.png'/></tile>
<tile id='230'><image width='256' height='352' source='../Tiles/tree_pineLarge_S.png'/></tile>
<tile id='231'><image width='256' height='352' source='../Tiles/tree_pineLarge_W.png'/></tile>
<tile id='232'><image width='256' height='352' source='../Tiles/well_N.png'/></tile>
<tile id='233'><image width='256' height='352' source='../Tiles/well_E.png'/></tile>
<tile id='234'><image width='256' height='352' source='../Tiles/well_S.png'/></tile>
<tile id='235'><image width='256' height='352' source='../Tiles/well_W.png'/></tile>

</tileset>
